site_name: ZhaoCake's文档翻译
site_description: 文档翻译中文翻译
# site_author: Chisel Community
repo_url: https://github.com/ZhaoCake/translation_docs
repo_name: ZhaoCake/translation_docs

theme:
  name: material
  language: zh
  logo: assets/zhao.png
  favicon: assets/zhao.jpg
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.path
    - toc.follow
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.code.select
  palette:
    # Palette toggle for auto mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: 切换到浅色模式
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: grey
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: grey
      toggle:
        icon: material/brightness-4
        name: 切换到自动模式
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji
  - tables
  - toc:
      permalink: true

plugins:
  - search

nav:
  - 首页: index.md
  - Chisel Cookbooks:
    - 手册概述: chisel_cookbooks/index.md
    - 通用技巧(cookbook): chisel_cookbooks/cookbook.md
    - 命名(naming): chisel_cookbooks/naming.md
    - 层次结构(hierarchy): chisel_cookbooks/hierarchy.md
    - DataView: chisel_cookbooks/dataview.md
    - 序列化(serialization): chisel_cookbooks/serialization.md
    - 对象模型(objectmodel): chisel_cookbooks/objectmodel.md
    - 测试(testing): chisel_cookbooks/testing.md
    - 故障排除(troubleshooting): chisel_cookbooks/troubleshooting.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ZhaoCake
    - icon: fontawesome/brands/qq
      link: tencent://message/?uin=2317634877&Site=&Menu=yes
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1711392619
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/42-48-12-1

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
